-- MySQL Script generated by MySQL Workbench
-- seg 13 set 2021 23:25:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notesdb` ;
USE `notesdb` ;

-- -----------------------------------------------------
-- Table `notesdb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `periodo` TINYINT NOT NULL,
  `link` VARCHAR(100) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Disciplina_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idDisciplina`),
  CONSTRAINT `fk_Disciplina_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `notesdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Anotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Anotacao` (
  `idAnotacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `dataCriacao` TIMESTAMP NOT NULL,
  `dataEdicao` TIMESTAMP NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `conteudo` LONGTEXT NULL,
  PRIMARY KEY (`idAnotacao`),
  INDEX `fk_Anotacao_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Anotacao_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `notesdb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `prioridade` INT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Horario` (
  `dia` TINYINT NULL,
  `inicio` TIME NOT NULL,
  `fim` TIME NULL,
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horario_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `notesdb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Anotacao_has_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Anotacao_has_Tag` (
  `Tag_idTag` INT NOT NULL,
  `Anotacao_idAnotacao` INT NOT NULL,
  `idAnotacao_has_Tag` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAnotacao_has_Tag`),
  INDEX `fk_Tag_has_Anotacao_Anotacao1_idx` (`Anotacao_idAnotacao` ASC) VISIBLE,
  INDEX `fk_Tag_has_Anotacao_Tag1_idx` (`Tag_idTag` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_has_Anotacao_Tag1`
    FOREIGN KEY (`Tag_idTag`)
    REFERENCES `notesdb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Anotacao_Anotacao1`
    FOREIGN KEY (`Anotacao_idAnotacao`)
    REFERENCES `notesdb`.`Anotacao` (`idAnotacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notesdb`.`Credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notesdb`.`Credencial` (
  `idCredencial` INT NOT NULL AUTO_INCREMENT,
  `hashSenha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCredencial`, `Usuario_idUsuario`),
  INDEX `fk_Credencial_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Credencial_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `notesdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
